;;; flycheck-swift-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-swift.el

(autoload 'flycheck-swift-setup "flycheck-swift" "\
Setup Flycheck for Swift." t)
(register-definition-prefixes "flycheck-swift" '("flycheck-swift-prepend-for-cc-include-search-path"))

;;; End of scraped data

(provide 'flycheck-swift-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-swift-autoloads.el ends here
