;;; flycheck-swiftlint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-swiftlint.el

(autoload 'flycheck-swiftlint-setup "flycheck-swiftlint" "\
Setup Flycheck for Swiftlint." t)
(autoload 'flycheck-swiftlint-autocorrect "flycheck-swiftlint" "\
Automatically fix Swiftlint errors." t)
(register-definition-prefixes "flycheck-swiftlint" '("flycheck-swiftlint-"))

;;; End of scraped data

(provide 'flycheck-swiftlint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-swiftlint-autoloads.el ends here
